language: lisp

env:
  matrix:
#    - LISP=abcl
    - LISP=sbcl
#    - LISP=sbcl32
#    - LISP=ccl
#    - LISP=ccl32
#    - LISP=clisp
#    - LISP=clisp32
#    - LISP=cmucl
#    - LISP=ecl

#matrix:
#  allow_failures:
#    - env: LISP=sbcl

install:
  - curl https://raw.github.com/luismbo/cl-travis/master/install.sh | sh
  - git clone --depth=1 git://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  - git clone --depth=1 git://common-lisp.net/projects/alexandria/alexandria.git ~/lisp/alexandria
  - git clone --depth=1 git://github.com/cl-babel/babel.git ~/lisp/babel

script:
  - cl-launch -i "(load \"$HOME/quicklisp/setup.lisp\")
                  (ql:quickload :cffi-tests)
                  (asdf:test-system :cffi)
                  (unless (null (rtest:pending-tests))
                    (uiop:quit 1))"
